# Generated by Django 3.0.9 on 2020-08-30 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Question title"),
                ),
                ("clarification", models.TextField(verbose_name="Clarification")),
                (
                    "author_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asker",
                    ),
                ),
            ],
            options={"verbose_name": "Question", "verbose_name_plural": "Questions",},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(max_length=20, unique=True, verbose_name="Tag"),
                ),
                (
                    "tagged_questions",
                    models.ManyToManyField(
                        to="forum.Question", verbose_name="tagged Question"
                    ),
                ),
            ],
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags",},
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Answer")),
                (
                    "author_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Answerer",
                    ),
                ),
            ],
            options={"verbose_name": "Answer", "verbose_name_plural": "Answers",},
        ),
    ]
